# Config file based on http://genbattle.bitbucket.org/blog/2016/01/17/c++-travis-ci/

sudo: required
dist: trusty
language: cpp

notifications:
  email: false

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env:
		- COMPILER=g++-4.9
		- OPENCV_VERSION=2.4.13
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env:
	    - COMPILER=g++-4.9
		- OPENCV_VERSION=3.0
	- compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env:
	    - COMPILER=g++-4.9
		- OPENCV_VERSION=3.1

before_install:
  - sudo apt-get update -qq
		
install:
    - ./.travis/install.sh 

script:
  - mkdir build.release
  - cd build.release
  - cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=$COMPILER
  - make -j4
  - cd ..
  - mkdir build.debug
  - cd build.debug
  - cmake .. -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_COMPILER=$COMPILER
  - make -j4
